apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: overleaf-ingress
  namespace: overleaf
  labels:
    app: overleaf
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: {{ .Values.ingress.ingressClassName }}
  tls:
    - hosts:
        - {{ .Values.ingress.host }}
      secretName: overleaf-tls
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: overleaf
                port:
                  number: 80
