apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-storage-manual
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: overleaf-pv
spec:
  capacity:
    storage: {{ .Values.overleaf.storage.size }}
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage-manual
  local:
    path: /mnt/data/overleaf
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - machine4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: overleaf-pvc
  namespace: overleaf
  labels:
    app: overleaf
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage-manual
  resources:
    requests:
      storage: {{ .Values.overleaf.storage.size }}
