apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: overleaf-pvc
  namespace: overleaf
  labels:
    app: overleaf
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.overleaf.storage.storageClass }}
  resources:
    requests:
      storage: {{ .Values.overleaf.storage.size }}
